### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by r-lyeh-archived** [evanw/gl4#1]
hello evanw

what's the license for this? 
could you add a LICENSE file please?

ta,
rlyeh

ps: nice work you did on here : ) concise, tiny and without dependencies. a pure joy.

**Comment by r-lyeh-archived** [comment]
ping @evanw

**Comment by evanw** [comment]
Whoops, sorry. Released under [CC0](https://creativecommons.org/publicdomain/zero/1.0/). Use it for whatever you want :)

**Comment by r-lyeh-archived** [comment]
:+1: !

**Comment by r-lyeh-archived** [comment]
RT @procedural , who was interested in this as well long time ago
